openapi: "3.0.0"
info:
  title: TODO API Document
  version: "0.0.1"
  description: TODO API document
tags:
  - name: opts
    description: 運用監視関連API
  - name: tasks
    description: タスク関連API
paths:
  /health:
    get:
      tags:
        - opts
      responses:
        '200':
          description: OK
  /tasks/{taskId}:
    get:
      tags:
          - tasks
      # operationIdはメソッド名になる
      operationId: showTask
      parameters:
        - name: taskId
          in: path
          required: true
          description: "詳細取得するためのタスクID"
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskDTO'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundError'
components:
  schemas:
    TaskDTO:
      # レスポンスボディのjson Schema定義
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: "タスクID"
        title:
          type: string
          description: "タスクタイトル"
      required:
        - id
        - title
    ResourceNotFoundError:
      type: object
      description: "指定したリソースが存在しない"
      properties:
        title:
            type: string
            description: "エラータイトル"
            default: "Resource Not Found"
        detail:
            type: string
            description: "エラー詳細"
      required:
        - title
        - detail