openapi: "3.0.0"
info:
  title: TODO API Document
  version: "0.0.1"
  description: TODO API document
tags:
  - name: opts
    description: 運用監視関連API
  - name: tasks
    description: タスク関連API
paths:
  /health:
    get:
      tags:
        - opts
      responses:
        '200':
          description: OK
  /tasks/1:
    get:
      tags:
          - tasks
      # operationIdはメソッド名になる
      operationId: showTask
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskDTO'
components:
  schemas:
    TaskDTO:
      # レスポンスボディのjson Schema定義
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: "タスクID"
        title:
          type: string
          description: "タスクタイトル"
      required:
        - id
        - title