CREATE TABLE samples (
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    content VARCHAR(255) NOT NULL
);

CREATE TABLE tasks (
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL
);

CREATE TABLE users (
    id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL
);